from pydantic_ai import Agent
import os
from core.config import config

gemini_key = config.get('api_keys', {}).get('gemini_api', 'dummy_key')
os.environ.setdefault('GOOGLE_API_KEY', gemini_key if gemini_key != "YOUR_GEMINI_API_KEY" else 'dummy_key')

seo_agent = Agent(
    'gemini-1.5-flash',
    system_prompt="""You are the SEO Specialist for a digital media company.
    Your task is to take a generated script and initial metadata, and optimize it for the YouTube and Instagram algorithms.
    Enhance the title for high CTR, rewrite the description with keywords, and provide a list of highly relevant, trending hashtags.
    Output must be JSON with 'optimized_title', 'optimized_description', and 'optimized_tags' (list of strings).""",
)

async def optimize_metadata(content: dict) -> dict:
    """
    Optimizes the metadata generated by the creative agent.
    """
    prompt = f"Optimize this metadata: {content}"

    try:
        if os.environ.get('GOOGLE_API_KEY') == 'dummy_key':
            return {
                "optimized_title": f"🔥 {content.get('title')} | YOU WON'T BELIEVE THIS!",
                "optimized_description": f"Check out this amazing video! {content.get('description')} #viral #trending",
                "optimized_tags": content.get('tags', []) + ["viral", "trending", "mustwatch"]
            }

        result = await seo_agent.run(prompt)
        from core.utils import parse_llm_json
        data = parse_llm_json(result.data)
        return data
    except Exception as e:
        print(f"[SEO Agent] Error optimizing metadata: {e}")
        return {
            "optimized_title": content.get('title', 'Viral Video'),
            "optimized_description": content.get('description', 'Watch this amazing content!'),
            "optimized_tags": content.get('tags', [])
        }
